#!/usr/bin/env zsh

# Setup the basic environment
export TERM="xterm-256color"    # Use 256 colors in terminal
export EDITOR="vim"             # Set default editor to Neovim
export VISUAL="$EDITOR"         # Set visual editor to Neovim

export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
# export LS_COLORS="di=0;34:ln=0;36:so=0;35:pi=40;33:ex=0;32:bd=40;33;01:cd=40;33;01:su=0;37;41:sg=0;30;43:tw=0;34;42:ow=0;34;42"
export GREP_OPTIONS='--color=auto'
export K_SHOW_GIT=1             # for 'k' to work with git status

# If you need to have curl first in your PATH, run:
export PATH="$(\brew --prefix)/opt/curl/bin:$PATH"
# For compilers to find curl you may need to set:
export LDFLAGS="-L/opt/homebrew/opt/curl/lib"
export CPPFLAGS="-I/opt/homebrew/opt/curl/include"

export HOMEBREW_INSTALL_BADGE="☕️ 🐸"
export HOMEBREW_INSTALL_BADGE_COLOR="green"

export ZSH_HISTORY_SEARCH_STYLE="bashlike"  # Cursor at end (default), or use "zshlike"